services:
  nats:
    image: nats:2.10
    ports: ["4222:4222", "8222:8222"]
    command: "-js -m 8222"
    networks: [mess-net]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports: ["5432:5432"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks: [mess-net]

  # 3. Auth Service (с новым именем 'auth')
  auth: # <-- ИЗМЕНЕНИЕ
    build:
      context: .
      dockerfile: services/auth/Dockerfile # <-- ИЗМЕНЕНИЕ
    environment:
      NATS_URL: "nats://nats:4222"
      JWT_SECRET: "my-super-secret-key-for-jwt-12345"
      JWT_ISSUER: "org.mess.backend"
      DB_URL: "jdbc:postgresql://postgres:5432/auth_db"
      DB_USER: "admin"
      DB_PASS: "admin_password"
    depends_on: [nats, postgres]
    networks: [mess-net]

  # 4. User Service (с новым именем 'user')
  user: # <-- ИЗМЕНЕНИЕ
    build:
      context: .
      dockerfile: services/user/Dockerfile # <-- ИЗМЕНЕНИЕ
    environment:
      NATS_URL: "nats://nats:4222"
      DB_URL: "jdbc:postgresql://postgres:5432/user_db"
      DB_USER: "admin"
      DB_PASS: "admin_password"
    depends_on: [nats, postgres]
    networks: [mess-net]

  # 5. Chat Service (с новым именем 'chat')
  chat: # <-- ИЗМЕНЕНИЕ
    build:
      context: .
      dockerfile: services/chat/Dockerfile # <-- ИЗМЕНЕНИЕ
    environment:
      NATS_URL: "nats://nats:4222"
      DB_URL: "jdbc:postgresql://postgres:5432/chat_db"
      DB_USER: "admin"
      DB_PASS: "admin_password"
    depends_on:
      - nats
      - postgres
      - user # <-- ИЗМЕНЕНИЕ
    networks: [mess-net]

  # 6. Gateway (остается без изменений, но его зависимости обновлены)
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports: ["8080:8080"] # gRPC-сервер
    environment:
      NATS_URL: "nats://nats:4222"
      JWT_SECRET: "my-super-secret-key-for-jwt-12345"
      JWT_ISSUER: "org.mess.backend"
    depends_on:
      - nats
      - auth # <-- ИЗМЕНЕНИЕ
      - user # <-- ИЗМЕНЕНИЕ
      - chat # <-- ИЗМЕНЕНИЕ
    networks: [mess-net]

volumes:
  postgres-data:

networks:
  mess-net:
    driver: bridge